# Generated by Django 3.2.6 on 2023-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atcdpo', models.TextField(blank=True, null=True)),
                ('comatcdpo', models.TextField(blank=True, null=True)),
                ('atcdfogl', models.CharField(max_length=255)),
                ('atcdnumdoss', models.IntegerField()),
                ('atcddmla', models.CharField(max_length=255)),
                ('atcdaller', models.CharField(max_length=255)),
                ('atcdco', models.CharField(max_length=255)),
                ('atcdce', models.CharField(max_length=255)),
                ('atcdfammedhta', models.CharField(max_length=255)),
                ('atcdfamdiab', models.CharField(max_length=255)),
                ('atcdfamavc', models.CharField(max_length=255)),
                ('comatcdfammed', models.TextField(blank=True, null=True)),
                ('comatcdfammedical', models.TextField(blank=True, null=True)),
                ('atcdsocio', models.TextField(blank=True, null=True)),
                ('comatcdfamoph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquete_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_num_doss', models.IntegerField()),
                ('douleur', models.CharField(max_length=255)),
                ('larme', models.CharField(max_length=255)),
                ('picco', models.CharField(max_length=255)),
                ('prurit', models.CharField(max_length=255)),
                ('grains', models.CharField(max_length=255)),
                ('visuels', models.CharField(max_length=255)),
                ('meta', models.CharField(max_length=255)),
                ('photopsies', models.CharField(max_length=255)),
                ('myodesopsies', models.CharField(max_length=255)),
                ('Cephalees', models.CharField(max_length=255)),
                ('Otalgie', models.CharField(max_length=255)),
                ('acouphene', models.CharField(max_length=255)),
                ('nausees', models.CharField(max_length=255)),
                ('vomissement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodossier', models.IntegerField()),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=7)),
                ('etatcivil', models.CharField(max_length=40)),
                ('profession', models.CharField(max_length=40)),
                ('dateconsultation', models.DateField(verbose_name='%m/%d/%Y')),
                ('telephone', models.CharField(max_length=14)),
                ('assurer', models.CharField(max_length=3)),
                ('assurancesocial', models.CharField(blank=True, max_length=40)),
                ('nomassureur', models.CharField(blank=True, max_length=40)),
                ('domicile', models.CharField(max_length=40)),
                ('regionorigine', models.CharField(max_length=20)),
                ('statutmalade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motifcon', models.CharField(max_length=255)),
                ('plaintes', models.CharField(max_length=255)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=9)),
                ('obsnumdoss', models.IntegerField()),
            ],
        ),
    ]
