# Generated by Django 3.2.6 on 2023-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examnumdoss', models.IntegerField()),
                ('inspection', models.CharField(blank=True, max_length=255, null=True)),
                ('occulomotricite', models.CharField(blank=True, max_length=255, null=True)),
                ('avog', models.IntegerField(blank=True, null=True)),
                ('avod', models.IntegerField(blank=True, null=True)),
                ('piog', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('piod', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cosphere', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cocylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('coaxe', models.IntegerField(blank=True, null=True)),
                ('resphere', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('recylindre', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('reaxe', models.IntegerField(blank=True, null=True)),
                ('cdvaleur', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('annexes', models.CharField(blank=True, max_length=255, null=True)),
                ('iris', models.CharField(blank=True, max_length=255, null=True)),
                ('cristallin', models.CharField(blank=True, max_length=255, null=True)),
                ('vitre', models.CharField(blank=True, max_length=255, null=True)),
                ('macula', models.CharField(blank=True, max_length=255, null=True)),
                ('papille', models.CharField(blank=True, max_length=255, null=True)),
                ('pupil', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
