# Generated by Django 3.2.6 on 2023-09-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230925_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='cocylindre',
            new_name='accomod',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='cosphere',
            new_name='accomog',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='coaxe',
            new_name='axeod',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='reaxe',
            new_name='axeog',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='recylindre',
            new_name='cylindreod',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='resphere',
            new_name='cylindreog',
        ),
        migrations.AddField(
            model_name='exam',
            name='annexesod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='caod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='corneeod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='cristallinod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='irisod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pupilod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='retineod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='sphereod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='sphereog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='vitreod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
