# Generated by Django 3.2.6 on 2023-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230925_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnumdoss', models.IntegerField()),
                ('diagnostiqueog', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostiqueod', models.CharField(blank=True, max_length=255, null=True)),
                ('commentairediag', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitnumdoss', models.IntegerField()),
                ('ccl', models.CharField(blank=True, max_length=255, null=True)),
                ('cat', models.TextField(blank=True, null=True)),
                ('suivi_maladie', models.TextField(blank=True, max_length=255, null=True)),
                ('Tout_rdv', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
