# Generated by Django 3.2.6 on 2023-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diagnostique_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='traiteencours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
