# Generated by Django 3.2.6 on 2023-09-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230928_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete_system',
            name='douleur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
