# Generated by Django 3.2.6 on 2023-10-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_enquete_system_douleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='nommedecin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='nompatient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
