# Generated by Django 3.2.6 on 2023-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20231008_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='nommedecin',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='nompatient',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
