# Generated by Django 3.2.6 on 2023-10-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20231008_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='accomod',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='accomog',
        ),
    ]
