# Generated by Django 3.2.6 on 2023-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20231009_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete_system',
            name='asthme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquete_system',
            name='autrees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquete_system',
            name='rhinorrhee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
