# Generated by Django 3.2.6 on 2023-10-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20231009_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedent',
            name='atcdsocio',
        ),
        migrations.RemoveField(
            model_name='antecedent',
            name='comatcdfamoph',
        ),
        migrations.RemoveField(
            model_name='antecedent',
            name='comatcdpo',
        ),
        migrations.AddField(
            model_name='antecedent',
            name='alcool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedent',
            name='fdb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedent',
            name='fumeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedent',
            name='lunettes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedent',
            name='medicaments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedent',
            name='ordinateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
