# Generated by Django 3.2.6 on 2023-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20231009_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='plaintes',
        ),
    ]
