# Generated by Django 3.2.6 on 2023-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_observation_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='dose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='duree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='prescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
