# Generated by Django 3.2.6 on 2023-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20231010_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='nommedecintr',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='nompatienttr',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
